
name: Simple Docker Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          docker build -t syedabdulrahman134/my-flix:latest .
          docker push syedabdulrahman134/my-flix:latest
      - name: Report CI/CD Status to Lambda
        if: always()
        run: |
          curl -X POST https://s9vgu74kk6.execute-api.us-east-1.amazonaws.com/default/CICDPipelineNotifier \
            -H "Content-Type: application/json" \
            -d '{
              "status": "${{ job.status }}",
              "stage": "build & push",
              "commit": "${{ github.sha }}",
              "branch": "${{ github.ref_name }}",
              "repository": "${{ github.repository }}",
              "message": "Docker image pushed",
              "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
            }'
